# Generated by Django 3.1.2 on 2021-04-30 05:23

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='group',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='limits',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Ограничение 1', 'Ограничение 1'), ('Ограничение 2', 'Ограничение 2'), ('Ограничение 3', 'Ограничение 3')], max_length=41),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Умение Работать в Команде', 'Умение Работать в Команде'), ('git', 'git'), ('Проведение Уроков', 'Проведение Уроков')], max_length=47),
        ),
    ]
