# Generated by Django 3.1.2 on 2021-05-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0006_favv'),
    ]

    operations = [
        migrations.AddField(
            model_name='favv',
            name='note',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
