# Generated by Django 3.1.2 on 2021-05-20 02:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0007_favv_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='favv',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
