# Generated by Django 3.1.2 on 2021-06-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0008_favv_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='wage',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='group',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
