# Generated by Django 3.1.2 on 2021-06-20 08:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0009_auto_20210616_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='apartment',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='limits',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Речевые ограничения;', 'Речевые ограничения;'), ('Слабый слух;', 'Слабый слух;'), ('Нарушенная координация;', 'Нарушенная координация;')], max_length=57),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='wage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
